# Done to increase the memory available.
org.gradle.jvmargs=-Xmx3G

#Loom
loom_version=1.17-SNAPSHOT

#Modrinth
modrinth_versions=["1.21", "1.21.1"]

#`release`, `beta` or `alpha`
release_channel=beta
modrinth_id=eden-ring-reforked

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
fabric_version=0.156.0+26.2

# Mod Properties
mod_version=0.9.0-alpha.1
maven_group=paulevs.edenring
archives_base_name=eden-ring-reforked
