# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

#Modrinth
modrinth_versions=["26.1.2"]

#`release`, `beta` or `alpha`
release_channel=beta
modrinth_id=eden-ring-reforked

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.1
loom_version=1.16-SNAPSHOT

#Fabric api
fabric_version=0.145.4+26.1.2

# Mod Properties
mod_version=0.8.0
maven_group=paulevs.edenring
archives_base_name=eden-ring
