# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G

#Loom
loom_version=1.7-SNAPSHOT

#Modrinth
modrinth_versions=["1.21", "1.21.1"]

#`release`, `beta` or `alpha`
release_channel=beta
modrinth_id=eden-ring-reforked

# Fabric Properties
minecraft_version=1.21.1
loader_version=0.16.7

#Fabric api
fabric_version=0.105.0+1.21.1

# Mod Properties
mod_version=0.8.1-beta.3
maven_group=paulevs.edenring
archives_base_name=eden-ring-reforked

# Dependencies
bclib_version = 21.0.13
wover_version = 21.0.13
